name: Release on Merge

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build packages
        run: yarn build
      
      - name: Check UI changes
        id: ui-changes
        run: |
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q "^packages/ui/"; then
            echo "has-ui-changes=true" >> $GITHUB_OUTPUT
          else
            echo "has-ui-changes=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Check Utils changes
        id: utils-changes
        run: |
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q "^packages/utils/"; then
            echo "has-utils-changes=true" >> $GITHUB_OUTPUT
          else
            echo "has-utils-changes=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Release UI Package
        if: steps.ui-changes.outputs.has-ui-changes == 'true'
        env:
          NODE_ENV: production
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd packages/ui
          yarn release
      
      - name: Release Utils Package
        if: steps.utils-changes.outputs.has-utils-changes == 'true'
        env:
          NODE_ENV: production
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd packages/utils
          yarn release
